spring:
  application:
    name: JournalApp

  data:
    mongodb:
      uri: mongodb+srv://root:${DB_PASSWORD}@cluster0.pq557.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb


server:
  port: 1111

springdoc:
  swagger-ui:
    enabled: true
