spring:
  application:
    name: JournalApp

  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.pq557.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ${DB_NAME}


server:
  port: ${PORT}

springdoc:
  swagger-ui:
    enabled: true
